declare module "@ipareddes/ui-components" {
  import * as React from "react"

  // UI Components
  export const Accordion: React.FC<any>
  export const AccordionContent: React.FC<any>
  export const AccordionItem: React.FC<any>
  export const AccordionTrigger: React.FC<any>
  export const Alert: React.FC<any>
  export const AlertDescription: React.FC<any>
  export const AlertTitle: React.FC<any>
  export const Avatar: React.FC<any>
  export const AvatarFallback: React.FC<any>
  export const AvatarImage: React.FC<any>
  export const Badge: React.FC<any>
  export const Breadcrumb: React.FC<any>
  export const BreadcrumbEllipsis: React.FC<any>
  export const BreadcrumbItem: React.FC<any>
  export const BreadcrumbLink: React.FC<any>
  export const BreadcrumbList: React.FC<any>
  export const BreadcrumbPage: React.FC<any>
  export const BreadcrumbSeparator: React.FC<any>
  export const Button: React.FC<any>
  export const buttonVariants: (props?: any) => string
  export const Calendar: React.FC<any>
  export const Card: React.FC<any>
  export const CardContent: React.FC<any>
  export const CardDescription: React.FC<any>
  export const CardFooter: React.FC<any>
  export const CardHeader: React.FC<any>
  export const CardTitle: React.FC<any>
  export const Carousel: React.FC<any>
  export const CarouselContent: React.FC<any>
  export const CarouselItem: React.FC<any>
  export const CarouselNext: React.FC<any>
  export const CarouselPrevious: React.FC<any>
  export type CarouselApi = any
  export const Checkbox: React.FC<any>
  export const Collapsible: React.FC<any>
  export const CollapsibleContent: React.FC<any>
  export const CollapsibleTrigger: React.FC<any>
  export const Command: React.FC<any>
  export const CommandDialog: React.FC<any>
  export const CommandEmpty: React.FC<any>
  export const CommandGroup: React.FC<any>
  export const CommandInput: React.FC<any>
  export const CommandItem: React.FC<any>
  export const CommandList: React.FC<any>
  export const CommandSeparator: React.FC<any>
  export const CommandShortcut: React.FC<any>
  export const Dialog: React.FC<any>
  export const DialogClose: React.FC<any>
  export const DialogContent: React.FC<any>
  export const DialogDescription: React.FC<any>
  export const DialogFooter: React.FC<any>
  export const DialogHeader: React.FC<any>
  export const DialogOverlay: React.FC<any>
  export const DialogPortal: React.FC<any>
  export const DialogTitle: React.FC<any>
  export const DialogTrigger: React.FC<any>
  export const DropdownMenu: React.FC<any>
  export const DropdownMenuCheckboxItem: React.FC<any>
  export const DropdownMenuContent: React.FC<any>
  export const DropdownMenuGroup: React.FC<any>
  export const DropdownMenuItem: React.FC<any>
  export const DropdownMenuLabel: React.FC<any>
  export const DropdownMenuPortal: React.FC<any>
  export const DropdownMenuRadioGroup: React.FC<any>
  export const DropdownMenuRadioItem: React.FC<any>
  export const DropdownMenuSeparator: React.FC<any>
  export const DropdownMenuShortcut: React.FC<any>
  export const DropdownMenuSub: React.FC<any>
  export const DropdownMenuSubContent: React.FC<any>
  export const DropdownMenuSubTrigger: React.FC<any>
  export const DropdownMenuTrigger: React.FC<any>
  export const Form: React.FC<any>
  export const FormControl: React.FC<any>
  export const FormDescription: React.FC<any>
  export const FormField: React.FC<any>
  export const FormItem: React.FC<any>
  export const FormLabel: React.FC<any>
  export const FormMessage: React.FC<any>
  export const HoverCard: React.FC<any>
  export const HoverCardContent: React.FC<any>
  export const HoverCardTrigger: React.FC<any>
  export const Input: React.FC<any>
  export const InputOTP: React.FC<any>
  export const InputOTPGroup: React.FC<any>
  export const InputOTPSeparator: React.FC<any>
  export const InputOTPSlot: React.FC<any>
  export const Label: React.FC<any>
  export const Pagination: React.FC<any>
  export const PaginationContent: React.FC<any>
  export const PaginationEllipsis: React.FC<any>
  export const PaginationItem: React.FC<any>
  export const PaginationLink: React.FC<any>
  export const PaginationNext: React.FC<any>
  export const PaginationPrevious: React.FC<any>
  export const Popover: React.FC<any>
  export const PopoverContent: React.FC<any>
  export const PopoverTrigger: React.FC<any>
  export const RadioGroup: React.FC<any>
  export const RadioGroupItem: React.FC<any>
  export const ScrollArea: React.FC<any>
  export const ScrollBar: React.FC<any>
  export const Select: React.FC<any>
  export const SelectContent: React.FC<any>
  export const SelectGroup: React.FC<any>
  export const SelectItem: React.FC<any>
  export const SelectLabel: React.FC<any>
  export const SelectSeparator: React.FC<any>
  export const SelectTrigger: React.FC<any>
  export const SelectValue: React.FC<any>
  export const Separator: React.FC<any>
  export const Sheet: React.FC<any>
  export const SheetClose: React.FC<any>
  export const SheetContent: React.FC<any>
  export const SheetDescription: React.FC<any>
  export const SheetFooter: React.FC<any>
  export const SheetHeader: React.FC<any>
  export const SheetOverlay: React.FC<any>
  export const SheetPortal: React.FC<any>
  export const SheetTitle: React.FC<any>
  export const SheetTrigger: React.FC<any>
  export const Skeleton: React.FC<any>
  export const Slider: React.FC<any>
  export const Switch: React.FC<any>
  export const Table: React.FC<any>
  export const TableBody: React.FC<any>
  export const TableCaption: React.FC<any>
  export const TableCell: React.FC<any>
  export const TableFooter: React.FC<any>
  export const TableHead: React.FC<any>
  export const TableHeader: React.FC<any>
  export const TableRow: React.FC<any>
  export const Tabs: React.FC<any>
  export const TabsContent: React.FC<any>
  export const TabsList: React.FC<any>
  export const TabsTrigger: React.FC<any>
  export const Textarea: React.FC<any>
  export const Toggle: React.FC<any>
  export const ToggleGroup: React.FC<any>
  export const ToggleGroupItem: React.FC<any>
  export const Tooltip: React.FC<any>
  export const TooltipContent: React.FC<any>
  export const TooltipProvider: React.FC<any>
  export const TooltipTrigger: React.FC<any>
  export const Toaster: React.FC<any>
  export const toast: any
  export const useFormField: () => any

  // Blocks
  export const BlockPreview: React.FC<any>
  export const CodeBlock: React.FC<any>
  export const FeatureSection2: React.FC<any>
  export const FeatureSection3: React.FC<any>
  export const FeatureSection4: React.FC<any>
  export const FeatureSection21: React.FC<any>

  // Lib
  export const cn: (...args: any[]) => string
}
